trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: disable.coverage.autogenerate
  value: true

steps:
- bash: 'docker-compose -f ./docker-compose-testapi.yml up unit integration e2e'
  displayName: 'Docker Compose Test'

- bash: 'docker-compose -f ./docker-compose-testapi.yml up coverage'
  displayName: 'Docker Compose Coverage'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/*.trx'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    mergeTestResults: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from **/Cobertura.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/Cobertura.xml'
    reportDirectory: '/app/results'